# 빌드 단계
FROM node:20.11.0 as build
WORKDIR /FE
COPY package.json /FE/
RUN npm install
COPY . /FE
ENV NODE_OPTIONS=--openssl-legacy-provider
RUN npm run build

# 실행 단계
FROM nginx:alpine
COPY --from=build /FE/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
